Processing text file...
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-3-1047b082c881> in <module>
    250     print("Processing text file...")
    251     text_results = processor.process_file(r'C:\Users\2011747\Desktop\TEST\email.txt')
--> 252     print(f"Requester: {text_results[0]['requester']}")
    253     print(f"Approver: {text_results[0]['approver']}")
    254     print(f"Status: {text_results[0]['status']}")

KeyError: 0
