Job failed: Error in Python process: At line 24: <class 'Exception'>: Folder is not on the local filesystem (uses HDFS), cannot perform direct filesystem access. Use the read/write API instead. More info about this error
